spring.application.name=test

# ===============================
# Server
# ===============================
server.port=9090

# ===============================
# Logging
# ===============================
logging.file.name=logs/app.log
logging.level.root=INFO
logging.level.com.example.demo=DEBUG

# ===============================
# Disable DB (LOCAL RUN)
# ===============================
# Disable DB + JPA completely for tests
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
spring.jpa.repositories.enabled=false
payment.default.type=DUMMY
payment.params.bank_account_number=0000000000
payment.params.bank_ifsc_code=TEST0000001
payment.params.bank_account_name=TEST_ACCOUNT
payment.params.currency=INR
payment.params.bank_code=TEST_BANK