

# ONDC headers
header.subscriberId=ondcstaging.canvendor.co.in
header.uniqueKeyId=1f29e8b1-feaf-4981-8d66-45db3a05ab9e
header.privateKey=oNwNy1cp6RPMxKdvFcCMOHqVPUbj5HNBvTtZOdFFnFM=

# ONDC URLs
api.bap.url=https://ondcstaging.canvendor.co.in/
api.search.url=https://staging.gateway.proteantech.in/search


# DB (Staging)
spring.datasource.url=jdbc:mysql://192.168.0.46:3306/ondc_buyer_motor
spring.datasource.username=chennai_canvendor
spring.datasource.password=Can12345
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# JWT
app.jwtAuthTokenSecret=qmhkxoEl9v4t1TVbjqKXJjWOPZEkSMUzICRHhpRtA04=