
# ONDC headers
header.subscriberId=ondcpreprod.canvendor.co.in
header.uniqueKeyId=1f29e8b1-feaf-4981-8d66-45db3a05ab9e
header.privateKey=hTTtkkugg7kvQefRehO/4f1a7vrJGwGJeByRZMbCsrg=

# ONDC URLs
api.search.url=https://preprod.gateway.ondc.org/search
api.bap.url=https://ondcpreprod.canvendor.co.in/bap

# DB (preprod)
spring.datasource.url=jdbc:mysql://192.168.0.46:3306/ondc_buyer_motor
spring.datasource.username=chennai_canvendor
spring.datasource.password=Can12345
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# JWT
app.jwtAuthTokenSecret=qmhkxoEl9v4t1TVbjqKXJjWOPZEkSMUzICRHhpRtA04=